export const path = {
    HOME: '/',
    HOME_PAGE: '/home',
    APP: '/app',
    LOGIN: '/login',
    SIGNUP: '/signup',
    USER_DASHBOARD: '/dashboard/user',
    SELLER_DASHBOARD: '/dashboard/seller',
    ADMIN_DASHBOARD: '/dashboard/admin',
    UNAUTHORIZED: '/unauthorized',
    PROFILE: '/profile',
    PRODUCT: '/product/:productId',
    SELLER_MENU: {
        MONITOR: '/dashboard/seller/monitor',
        PRODUCTS: '/dashboard/seller/products',
        ORDERS: '/dashboard/seller/orders',
        MESSAGE: '/dashboard/seller/message',
        COUPON: '/dashboard/seller/coupon',
        PAYMENT: '/dashboard/seller/payment'
    },
    CHECKOUT: '/checkout',
    CART: '/cart',
    ORDERS: '/orders',
    VIEWORDER: '/orders/:orderId',
    CHECKOUT_SUCCESS: '/order-success',
    SUPPORT: '/support',
    TOPUP: '/topup',
    ABOUT: '/about',
    ALL_PRODUCTS: '/products'
}